server:
  port: 9091

spring:
  datasource:
    url: jdbc:mysql://localhost:4677/raji
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    hibernate.ddl-auto: update
message: this is dev env

eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:1010/eureka
    